apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  eventKey: {{ .Values.secrets.eventKey | quote }}
  signingKey: {{ .Values.secrets.signingKey | quote }}
